# 1 create a 3x3x3 array with random values

In [1]:
import numpy as np
e=np.empty([3,3])
e

array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 6.996e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

# 2 create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
e=np.diag([0,1,2,3,4])
e

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

# 3 Create a 8x8 matrix and fill it with a checkerboard pattern

In [13]:
x=np.zeros((8,8),dtype=int)
x

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

# 4 Normalize a 5x5 random matrix

In [23]:
import numpy as np

# Create a 5x5 random matrix
matrix = np.random.rand(5,5)


min_val = matrix.min()
max_val = matrix.max()


normalized_matrix = (matrix - min_val)/(max_val - min_val)

print("Original Matrix:")
print(matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.32796731 0.35791998 0.02049289 0.9137475  0.36805221]
 [0.73740037 0.26641267 0.01540804 0.2298848  0.16038949]
 [0.30158561 0.81576119 0.31870388 0.33680919 0.35369044]
 [0.25840995 0.52528655 0.74878556 0.94991501 0.64600043]
 [0.64302601 0.0081007  0.01986146 0.87145228 0.08375599]]

Normalized Matrix:
[[0.33962811 0.37143126 0.01315778 0.96159805 0.38218947]
 [0.77435612 0.27427059 0.00775878 0.23548601 0.16169725]
 [0.31161654 0.8575581  0.32979237 0.34901624 0.36694042]
 [0.26577345 0.54913781 0.78644469 1.         0.67730945]
 [0.67415127 0.         0.01248733 0.91668982 0.0803293 ]]


# 5 how to find common values between two arrays

In [26]:
array1=np.array([1,5,6,3,2])
array2=np.array([9,6,8,7,2])
c_element=np.intersect1d(array1,array2)
print(f"The comman elements in the arrays are {c_element}")

The comman elements in the arrays are [2 6]


# 6 how to get the dates of yesterday, today and tomorrow

In [29]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Calculate yesterday's date
yesterday = today - timedelta(days=1)

# Calculate tomorrow's date
tomorrow = today + timedelta(days=1)

# Format the dates as strings if needed
today_str = today.strftime("%Y-%m-%d")
yesterday_str = yesterday.strftime("%Y-%m-%d")
tomorrow_str = tomorrow.strftime("%Y-%m-%d")

print("Yesterday --->", yesterday_str)
print("Today ---->", today_str)
print("Tomorrow --->", tomorrow_str)


Yesterday ---> 2023-09-20
Today ----> 2023-09-21
Tomorrow ---> 2023-09-22


# 7 Consider two random array Aand B check if they are equal

In [ ]:
array1=np.random.randint(0, 10, size=5)
array2=np.random.randint(0, 10, size=5)
check_a= np.array_equal(array1, array2)
if check_a:
    print("They are equal")
else:
    print("There are not equal")

# 8 Create random vector of size 10 and replace the maximum value by 0

In [50]:
vect_pro = np.random.randint(0, 100, size=10)
max_value = np.argmax(vect_pro)
vect_pro[max_value] = 0
print("The Random Vector is:",vect_pro)

The Random Vector is: [12 42 10 19 53 66 26 88  0 98]


# 9 How to print all the values in the array

In [62]:
arr = np.array([1,5,6,2,3,4,8,9,5,7])

print(arr)
print(type(arr))

[1 5 6 2 3 4 8 9 5 7]
<class 'numpy.ndarray'>


# 10 subtract the mean of each row of a matrix

In [68]:
mat_1=np.array([[2,4,5],[4,6,8],[9,6,7]],dtype=int)
e = mat_1 - mat_1.mean(axis=1)
e


array([[-1.66666667, -2.        , -2.33333333],
       [ 0.33333333,  0.        ,  0.66666667],
       [ 5.33333333,  0.        , -0.33333333]])

# 11 Consider a given vector how to add 1 to each element indexed by second vector (be carefull with repeated indices)

In [71]:
vect=np.random.randn(10)

In [93]:
given_vector = [3, 8, 7, 6, 9]


indices_to_increment = [1, 3, 1, 4, 0]


for index in indices_to_increment:
    if 0 <= index < len(given_vector):
        given_vector[index] += 1


print("Result Vector:", given_vector)


Result Vector: [4, 10, 7, 7, 10]


# 12 how to get the diagonal of a dot product 

In [95]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

dot_arr = np.dot(arr1,arr2)

dia = np.diagonal(dot_arr)

print("The Dot Array is {}".format(dot_arr))
print("The Diagonal is {}".format(dia))

The Dot Array is [[19 22]
 [43 50]]
The Diagonal is [19 50]


# 13 how to find the most frequent value in an array

In [96]:
from collections import Counter

x = np.random.randint(0,10,50)



element_counts = Counter(x)


most_common_elements = element_counts.most_common()


most_common_value = most_common_elements[0][0] 

print("Array:", x)
print("Most Common Value:", most_common_value)



Array: [9 0 8 8 2 0 5 2 9 1 9 9 3 7 9 2 9 5 4 3 7 5 0 8 4 0 0 1 9 0 8 8 5 5 9 7 8
 8 5 5 3 4 4 8 2 7 6 2 1 5]
Most Common Value: 9


# 14 how to get the n largest element in the array

In [103]:
e=np.array([5,2,6,4,5,8,5,9,6,4,7,5,16,2,5,22])

n=1

largest_n_elements = np.partition(my_array, -n)[-n:]

print("Array:", e)
print(f"{n} Largest Elements:", largest_n_elements)




Array: [ 5  2  6  4  5  8  5  9  6  4  7  5 16  2  5 22]
1 Largest Elements: [9]


# 15 how to create a record array from regular array

# 16 how to swap two rows of an array

In [104]:
n=np.array([[2,6,8],[5,8,7],[1,6,7]])

n1_row=0
n2_row=2
n[n1_row],n[n2_row]=n[n2_row].copy(),n[n1_row].copy()
print(n)

[[1 6 7]
 [5 8 7]
 [2 6 8]]


# 17 Wite a python code to reshape to the next dimension of numpy array