# 1. What is the purpose of text preprocessing in NLP, and why is it essential before analysis?

Text preprocessing is an essential step in natural language processing (NLP) that involves cleaning and transforming unstructured text data to prepare it for analysis. It includes tokenization, stemming, lemmatization, stop-word removal, and part-of-speech tagging
1.Noise Reduction
2.Tokenization
3.Lowercasing
4.Stopword Removal
5.Stemming and Lemmatization

# 2. Describe tokenization in NLP and explain its significance in text processing.

Tokenization is a key (and mandatory) aspect of working with text data
We’ll discuss the various nuances of tokenization, including how to handle Out-of-Vocabulary words (OOV)
This process is essential for various natural language processing tasks, as it provides organized input for analysis. Tokenization plays a crucial role in tasks like sentiment analysis, language translation, and information retrieval, enabling better language understanding, feature extraction, and model comprehension.

In [10]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize

text="""The regularization parameter "C" in SVM controls the trade-off between maximizing the margin and minimizing training errors A small C focuses on maximizing the margin, potentially allowing some misclassifications (soft margin) and preventing overfitting"""
print('Original text:\n',text)
print()
tokenised_sent=sent_tokenize(text)
print('Aftr sentence Tokanization:\n',tokenised_sent)
print()
print('no of sentnces:\n',len(tokenised_sent))
print('='*70)
print()

print('Original text:\n',text)
print()
tokenised_word=word_tokenize(text)
print('Aftr word Tokanization:\n',tokenised_word)
print()
print('no of words:\n',len(tokenised_word))

Original text:
 The regularization parameter "C" in SVM controls the trade-off between maximizing the margin and minimizing training errors A small C focuses on maximizing the margin, potentially allowing some misclassifications (soft margin) and preventing overfitting

Aftr sentence Tokanization:
 ['The regularization parameter "C" in SVM controls the trade-off between maximizing the margin and minimizing training errors A small C focuses on maximizing the margin, potentially allowing some misclassifications (soft margin) and preventing overfitting']

no of sentnces:
 1

Original text:
 The regularization parameter "C" in SVM controls the trade-off between maximizing the margin and minimizing training errors A small C focuses on maximizing the margin, potentially allowing some misclassifications (soft margin) and preventing overfitting

Aftr word Tokanization:
 ['The', 'regularization', 'parameter', '``', 'C', "''", 'in', 'SVM', 'controls', 'the', 'trade-off', 'between', 'maximizing',

In [11]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to C:\Users\Prakash
[nltk_data]     Nani\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [12]:
from nltk.stem import PorterStemmer

ps=PorterStemmer()

stemmed_words=[]

for w in tokenised_word:
    stemmed_words.append(ps.stem(w))
    

print('='*70)
print('Tokenized words - without stemming:\n\n\t',tokenised_word)
print('='*70)
print('\nTokenized words - afer stemming are:\n\t',stemmed_words)

from nltk.stem import WordNetLemmatizer


lemma=WordNetLemmatizer()#Initilize the wordnet lemmatizer

#apply lemmatazion to each word
lemma_words=[lemma.lemmatize(word,pos='v') for word in tokenised_word ]#apply lemmatazion to each word

print('='*70)
print('lemmarized words:\n',lemma_words)

Tokenized words - without stemming:

	 ['The', 'regularization', 'parameter', '``', 'C', "''", 'in', 'SVM', 'controls', 'the', 'trade-off', 'between', 'maximizing', 'the', 'margin', 'and', 'minimizing', 'training', 'errors', 'A', 'small', 'C', 'focuses', 'on', 'maximizing', 'the', 'margin', ',', 'potentially', 'allowing', 'some', 'misclassifications', '(', 'soft', 'margin', ')', 'and', 'preventing', 'overfitting']

Tokenized words - afer stemming are:
	 ['the', 'regular', 'paramet', '``', 'c', "''", 'in', 'svm', 'control', 'the', 'trade-off', 'between', 'maxim', 'the', 'margin', 'and', 'minim', 'train', 'error', 'a', 'small', 'c', 'focus', 'on', 'maxim', 'the', 'margin', ',', 'potenti', 'allow', 'some', 'misclassif', '(', 'soft', 'margin', ')', 'and', 'prevent', 'overfit']
lemmarized words:
 ['The', 'regularization', 'parameter', '``', 'C', "''", 'in', 'SVM', 'control', 'the', 'trade-off', 'between', 'maximize', 'the', 'margin', 'and', 'minimize', 'train', 'errors', 'A', 'small', 'C', 

# 4. Explain the concept of stop words and their role in text preprocessing. How do they impact NLP tasks?

stop words usually refers to the most common words in a language. There is no universal list of stop words that is used by all NLP tools in common
What are stop words
Stopwords are the words: in any language which does not add much meaning to a sentence. They can safely be ignored without sacrificing the meaning of the sentence. For some search engines, these are some of the most common, short function words, such as the, is, at, which, and on. In this case, stop words can cause problems when searching for phrases that include them, particularly in names such as “The Who” or “Take That”
When to remove stop words: if we have a task of text classification or sentiment analysis then we should remove stop words as they do not provide any information to our model, i.e keeping out unwanted words out of our corpus, but if we have the task of language translation then stopwords are useful, as they have to be translated along with other word

In [13]:
from nltk.corpus import stopwords
stop_words=set(stopwords.words('english'))

filtered_tokens=[]
for w in tokenised_word:
    if w not in stop_words:
        filtered_tokens.append(w)
print('Length of words:\t',len(tokenised_word))
print('='*70)
print('Tokenized words - with stop words:\n\n\t',tokenised_word)
print('='*70)
print('Length after the remoal of stopwords:\t',len(filtered_tokens))
print('='*70)
print('\nTokenized words - afer removing the stopwords are:\n\t',filtered_tokens)

Length of words:	 39
Tokenized words - with stop words:

	 ['The', 'regularization', 'parameter', '``', 'C', "''", 'in', 'SVM', 'controls', 'the', 'trade-off', 'between', 'maximizing', 'the', 'margin', 'and', 'minimizing', 'training', 'errors', 'A', 'small', 'C', 'focuses', 'on', 'maximizing', 'the', 'margin', ',', 'potentially', 'allowing', 'some', 'misclassifications', '(', 'soft', 'margin', ')', 'and', 'preventing', 'overfitting']
Length after the remoal of stopwords:	 30

Tokenized words - afer removing the stopwords are:
	 ['The', 'regularization', 'parameter', '``', 'C', "''", 'SVM', 'controls', 'trade-off', 'maximizing', 'margin', 'minimizing', 'training', 'errors', 'A', 'small', 'C', 'focuses', 'maximizing', 'margin', ',', 'potentially', 'allowing', 'misclassifications', '(', 'soft', 'margin', ')', 'preventing', 'overfitting']


# 5. How does the process of removing punctuation contribute to text preprocessing in NLP? What are its benefits?

The second most common text processing technique is removing punctuations from the textual data. The punctuation removal process will help to treat each text equally. For example, the word data and data! are treated equally after the process of removal of punctuations. This process prevents interference with the understanding of language models and enhances tokenization accuracy by establishing clear word boundaries for NLP tasks.

In [15]:
words=[word for word in tokenised_word if word.isalpha()]

print('Original text:\n',text)
print('='*70)

print('after removing puntuations:\n')
print(words)

Original text:
 The regularization parameter "C" in SVM controls the trade-off between maximizing the margin and minimizing training errors A small C focuses on maximizing the margin, potentially allowing some misclassifications (soft margin) and preventing overfitting
after removing puntuations:

['The', 'regularization', 'parameter', 'C', 'in', 'SVM', 'controls', 'the', 'between', 'maximizing', 'the', 'margin', 'and', 'minimizing', 'training', 'errors', 'A', 'small', 'C', 'focuses', 'on', 'maximizing', 'the', 'margin', 'potentially', 'allowing', 'some', 'misclassifications', 'soft', 'margin', 'and', 'preventing', 'overfitting']


# 6. Discuss the importance of lowercase conversion in text preprocessing. Why is it a common step in NLP tasks

Lower casing: Converting a word to lower case (NLP -> nlp). Words like Book and book mean the same but when not converted to the lower case those two are represented as two different words in the vector space model (resulting in more dimensions). It is a common practice in NLP to ensure consistency in text processing.

In [16]:
lower_words=[word.lower() for word in tokenised_word]
print('Original text:\n',text)
print('='*70)

print('after lowering the case:\n')
print(lower_words)

Original text:
 The regularization parameter "C" in SVM controls the trade-off between maximizing the margin and minimizing training errors A small C focuses on maximizing the margin, potentially allowing some misclassifications (soft margin) and preventing overfitting
after lowering the case:

['the', 'regularization', 'parameter', '``', 'c', "''", 'in', 'svm', 'controls', 'the', 'trade-off', 'between', 'maximizing', 'the', 'margin', 'and', 'minimizing', 'training', 'errors', 'a', 'small', 'c', 'focuses', 'on', 'maximizing', 'the', 'margin', ',', 'potentially', 'allowing', 'some', 'misclassifications', '(', 'soft', 'margin', ')', 'and', 'preventing', 'overfitting']



# 7. Explain the term "vectorization" concerning text data. How does techniques like CountVectorizer contribute to text preprocessing in NLP ?

Hence the process of converting text into vector is called vectorization. By using CountVectorizer function we can convert text document to matrix of word count. Matrix which is produced here is sparse matrix. By using CountVectorizer on above document we get 5*15 sparse matrix of type numpy. This approach allows models to interpret text data for tasks like classification or clustering in NLP, ultimately enhancing model performance and accuracy.

In [17]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

vector=CountVectorizer()

x=vector.fit_transform(tokenised_word)

feature_names=vector.get_feature_names_out()

print('Feature names:\n',feature_names)
print('*'*70)
print('Token counts matrix:')
print(x.toarray())

Feature names:
 ['allowing' 'and' 'between' 'controls' 'errors' 'focuses' 'in' 'margin'
 'maximizing' 'minimizing' 'misclassifications' 'off' 'on' 'overfitting'
 'parameter' 'potentially' 'preventing' 'regularization' 'small' 'soft'
 'some' 'svm' 'the' 'trade' 'training']
**********************************************************************
Token counts matrix:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

# 8. Describe the concept of normalization in NLP. Provide examples of normalization techniques used in text preprocessing

Normalization in NLP seeks to convert diverse word forms into a standardized format, improving analysis by minimizing redundancy. Methods like stemming (shortening words to their root form, such as changing "running" to "run") and lemmatization (reducing words to their base or dictionary form, like transforming "better" to "good") play a role in standardizing text. Additionally, actions like Punctuation Removal and Stop Word Removal contribute to maintaining consistency in language representation. These practices enhance model comprehension and accuracy, particularly in tasks like sentiment analysis or information retrieval
1. Case Normalization
2. Punctuation Removal
3. Stop Word Removal
4. Stemming
5. Lemmatization
6. Tokenization